/*
 * This Scala source file was auto generated by running 'gradle buildInit --type scala-library'
 * by 'amit' at '9/2/14 9:59 PM' with Gradle 2.1-rc-1
 *
 * @author amit, @date 9/2/14 9:59 PM
 */
class Library {
  def someLibraryMethod(): Boolean = true
}
