/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'amit' at '5/15/16 10:10 PM' with Gradle 2.13
 *
 * @author amit, @date 5/15/16 10:10 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
