/*
 * This Scala Testsuite was auto generated by running 'gradle init --type scala-library'
 * by 'amit' at '9/2/14 9:59 PM' with Gradle 2.1-rc-1
 *
 * @author amit, @date 9/2/14 9:59 PM
 */

import org.scalatest.FunSuite
import org.junit.runner.RunWith
import org.scalatest.junit.JUnitRunner

@RunWith(classOf[JUnitRunner])
class LibrarySuite extends FunSuite {
  test("someLibraryMethod is always true") {
    def library = new Library()
    assert(library.someLibraryMethod)
  }
}
