/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'amit' at '9/2/14 9:58 PM' with Gradle 2.1-rc-1
 *
 * @author amit, @date 9/2/14 9:58 PM
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
