/*
 * This Spock specification was auto generated by running 'gradle init --type groovy-library'
 * by 'amit' at '9/2/14 9:58 PM' with Gradle 2.1-rc-1
 *
 * @author amit, @date 9/2/14 9:58 PM
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
